---
name: "newservice"
description: "Stop instance."
enabled: false

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    delta: 5
    unit: minutes

action:
  ref: "newservice.create-incident"
