---
name: "Create-incident_webhook"
description: "Create incident on service now."
enabled: false

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "create_incident_webhook"

action:
  ref: "service.create-incident"
criteria: {}
